// <auto-generated />
using IdentityApp.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace IdentityApp.Migrations
{
    [DbContext(typeof(ProductDbContext))]
    [Migration("20230916041922_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("IdentityApp.Models.Product", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .UseIdentityColumn();

                    b.Property<string>("Category")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(8,2)");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Category = "Watersports",
                            Name = "Kayak",
                            Price = 275m
                        },
                        new
                        {
                            Id = 2L,
                            Category = "Watersports",
                            Name = "Lifejacket",
                            Price = 48.99m
                        },
                        new
                        {
                            Id = 3L,
                            Category = "Football",
                            Name = "Ball",
                            Price = 19.50m
                        },
                        new
                        {
                            Id = 4L,
                            Category = "Football",
                            Name = "Corner Flags",
                            Price = 34.99m
                        },
                        new
                        {
                            Id = 5L,
                            Category = "Football",
                            Name = "Stadium",
                            Price = 88.99m
                        },
                        new
                        {
                            Id = 6L,
                            Category = "Football",
                            Name = "Baseball Cap",
                            Price = 21.99m
                        },
                        new
                        {
                            Id = 7L,
                            Category = "Football",
                            Name = "Scarf",
                            Price = 12.99m
                        },
                        new
                        {
                            Id = 8L,
                            Category = "Chess",
                            Name = "Chair",
                            Price = 46.99m
                        },
                        new
                        {
                            Id = 9L,
                            Category = "Chess",
                            Name = "Human-sized Chess Board",
                            Price = 75m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
